export enum InternalErrorCodeEnum {
  AUTHORIZATION_HEADER_MISSING = '001',
  AUTHORIZATION_HEADER_MALFORMED = '002',
  ACCESS_TOKEN_EXPIRED = '003',
  ACCESS_TOKEN_INVALID = '004',
  REFRESH_TOKEN_EXPIRED = '005',
  REFRESH_TOKEN_INVALID = '006',
  QUERY_ERROR = '007',
  DTO_VALIDATION_FAILED = '008',
  DTO_VALIDATION_UNKNOWN = '009',
  INVALID_CREDENTIALS = '010',
  UNEXPECTED_ROUTE = '011'
}
